version: "3"

services:
  fastapi-demo:
    image: fastapi-demo
    ports:
      - "2371-2372:8000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    restart: always
    volumes:
      - /data/projects/fastapi_template/:/app/:rw
      - ./config.ini:/app/config.ini
    command: ["python", "main.py"]
